
[urgency_low]
    background = "#A3786580"
    foreground = "#523529E6"
    frame_color = "#A3786503"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#F0CDAA80"
    foreground = "#523D29E6"
    frame_color = "#F0CDAA03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
