
[Wallbash]
text               = 523D29
subtext            = 6B523A
nav-active-text    = 7D644B
main               = F4E1C4
sidebar            = F4E1C4
player             = F4E1C4
card               = F4E1C4
shadow             = FFEBCC
main-secondary     = F0CDAA
button             = 6B493A
button-secondary   = 7D5A4B
button-active      = 8F6857
button-disabled    = F4E1C4
nav-active         = F0BFAA
play-button        = E6B09A
tab-active         = D0AB85
notification       = F4E1C4
notification-error = F4E1C4
playback-bar       = F4E1C4
misc               = D0AB85

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
